services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: commander
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5599:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
