spring:
  application:
    name: commander-server
  sql:
    init:
      mode: always
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
      republish-outstanding-events-on-restart: true

server:
  port: 7890

logging:
  level:
    edu.semitotal.commander: DEBUG
    org.springframework.modulith: DEBUG
